# Generated by Django 5.0.2 on 2024-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reg_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tbl',
            name='aeml',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reg_tbl',
            name='afnm',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='reg_tbl',
            name='amob',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reg_tbl',
            name='apsw',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='eml',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='fnm',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='psw',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
