# Generated by Django 5.0.2 on 2024-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reg_tbl_aeml_reg_tbl_afnm_reg_tbl_amob_reg_tbl_apsw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tbl',
            name='aeml',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='afnm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='amob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='apsw',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='eml',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='fnm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='mob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='psw',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
