# Generated by Django 5.0.2 on 2024-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reg_tbl_aeml_alter_reg_tbl_afnm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminreg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afnm', models.CharField(max_length=25)),
                ('amob', models.IntegerField()),
                ('aeml', models.EmailField(max_length=254)),
                ('apsw', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='reg_tbl',
        ),
    ]
