# Generated by Django 5.0.2 on 2024-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_adminreg_tbl_delete_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=25)),
                ('mob', models.IntegerField()),
                ('eml', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=25)),
            ],
        ),
    ]
