# Generated by Django 5.0.2 on 2024-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reg_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='seller',
            field=models.CharField(default='seller1', max_length=25),
        ),
    ]
