# Generated by Django 5.0.2 on 2024-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_tbl_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tbl',
            name='seller',
            field=models.CharField(default='seller1', max_length=25),
        ),
    ]
