# Generated by Django 5.0.2 on 2024-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnm', models.CharField(max_length=25)),
                ('prc', models.IntegerField()),
                ('des', models.TextField()),
                ('seller', models.CharField(default='seller1', max_length=25)),
            ],
        ),
    ]
