# Generated by Django 5.0.2 on 2024-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tbl',
            name='seller',
            field=models.CharField(max_length=25),
        ),
    ]
