# Generated by Django 5.0.2 on 2024-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_tbl_buyer_alter_order_tbl_opnm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='rentprice',
            field=models.IntegerField(default=10),
        ),
    ]
