# Generated by Django 5.0.2 on 2024-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_tbl_rentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tbl',
            name='rentprice',
            field=models.IntegerField(),
        ),
    ]
