# Generated by Django 5.0.2 on 2024-03-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_tbl_rentprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opnm', models.CharField(max_length=225)),
                ('Buyer', models.CharField(default='user', max_length=25)),
                ('oamount', models.IntegerField()),
                ('orentprice', models.IntegerField()),
                ('odes', models.TextField()),
                ('oseller', models.CharField(max_length=225)),
                ('odate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
