# Generated by Django 5.0.2 on 2024-03-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_rent_tbl_oduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_tbl',
            name='orentprice',
        ),
    ]
