# Generated by Django 5.0.2 on 2024-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_rent_tbl_orentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='quantity',
            field=models.IntegerField(default=3),
        ),
    ]
