# Generated by Django 5.0.2 on 2024-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_tbl_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='status',
            field=models.CharField(default='yes', max_length=10),
        ),
    ]
