# Generated by Django 5.0.2 on 2024-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product_tbl_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tbl',
            name='status',
        ),
        migrations.AlterField(
            model_name='product_tbl',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_tbl',
            name='seller',
            field=models.CharField(max_length=25),
        ),
    ]
