# Generated by Django 5.0.2 on 2024-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_product_tbl_status_alter_product_tbl_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hname', models.CharField(max_length=400)),
                ('street', models.CharField(max_length=400)),
                ('pincode', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
