# Generated by Django 5.0.2 on 2024-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='buyer',
            field=models.CharField(default='demo', max_length=200),
        ),
        migrations.AddField(
            model_name='order_payment',
            name='item',
            field=models.CharField(default='sample', max_length=200),
        ),
        migrations.AddField(
            model_name='order_payment',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
